### ISSUE TITLE
[Tracker] Search

### ISSUE THREAD

**Issue by meichthys** [pulsejet/memories#674]
Tracker issue for implementation of search.

- [x] Collaborative Tags
- [x] Recognize
- [x] Face Recognition
- [x] Albums
- [x] Places
- [ ] Dates (e.g. 2017 January)
- [ ] File Type (e.g. videos)
- [ ] Multiple categories
- [ ] FTS
- [ ] EXIF data (e.g. title/description)
- [ ] Search with synonyms (e.g. Drink => Beverage)
- [ ] Search with word forms (e.g. Animals => Animal)
- [ ] Localization

---
Original Post
---

[Semantic search](https://en.wikipedia.org/wiki/Semantic_search) would be a very welcome feature

**Describe the solution you'd like**
Semantic search allows searching using phrases rather than tags stored in a database. 

A search may be something like: boy wearing red shirt

**Describe alternatives you've considered**
Tags via Recognize are pretty good but searching multiple tags is cumbersome in Nextcloud

**Additional context**
I realize this may be limited by the existing nextcloud search functionality, but i wanted to file it here anyway since this type of semantic search is becoming more common in photo libraries.

**Comment by pulsejet** [comment]
A good semantic search is very complex, so much so that even Google Photos doesn't support this. Capturing context is fundamentally a very challenging task. For example, if we simply tokenize the input string, then `boy wearing red shirt` matches both of
1. `boy wearing red shirt`
2. `boy wearing blue shirt in red boat`

but _not_
1. `boy wearing red jersey`
2. `boy in red shirt`

A more realistic goal would be to support full text search on the existing tags (including faces), which can then be extended for simple queries, like `X and Y`.

**Comment by pulsejet** [comment]
Updated. Lots of tasks here, this one is tough.

**Comment by brianjmurrell** [comment]
I would agree that full semantic search is hard.

I would suggest that complex logical searches based on (all, but not necessarily immediately -- this can add more criteria incrementally -- of) the many criteria available in photos would be a great compromise.  Things like multiple tags, `and`ed and/or `or`ed, along with dates, date ranges, locations (with coverage radius), etc.

All of this metadata is almost useless without being able to use it in complex queries, IMO.

**Comment by brianjmurrell** [comment]
I would add two more criteria to your list: _untagged_ and _date-added_.

**Comment by yurividal** [comment]
Any updates on this? Search is still pretty useless at the moment. It always returns blank. Searching for file name is a basic thing...

**Comment by AndyH3H1** [comment]
I would love this, too. In Google Photos I often search for the description I manually added before. In memories the decription is shown on the bottom left in the picture. So maybe it´s possible to add this to the search. Same for the filename.

**Comment by nfnfgo** [comment]
> I would love this, too. In Google Photos I often search for the description I manually added before. In memories the decription is shown on the bottom left in the picture. So maybe it´s possible to add this to the search. Same for the filename.

Same issue here. Hope the search feature could work with basic EXIF text info like file name and description.
