### ISSUE TITLE
[Tracker] Viewer logic improvements

### ISSUE THREAD

**Issue by pulsejet** [pulsejet/memories#892]
- [x] Global count update (also anchor)
- [x] Prevent repeat preloading
- [x] Timeline: Mark destroyed day objects
- [x] Splice destroyed day object if encountered
- [x] Triage: what if timeline is soft/hard refreshed
